# Generated by Django 3.2.3 on 2021-05-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sworm', '0002_auto_20210523_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='citations',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='lda_topics',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
