# Generated by Django 3.2.3 on 2021-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sworm', '0003_auto_20210524_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='x1_coord',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='x2_coord',
            field=models.FloatField(null=True),
        ),
    ]
