# Generated by Django 3.2.3 on 2021-05-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sworm', '0005_auto_20210524_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='title',
            new_name='name',
        ),
    ]
