# Generated by Django 3.2.3 on 2021-05-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sworm', '0006_rename_title_journal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='x1_coord',
            new_name='x1',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='x2_coord',
            new_name='x2',
        ),
    ]
