version: "3"

services:
    sworm:
        image: docker.kondas.de/sworm-django
        container_name: sworm
        build: .
        volumes:
            - ./data/:/usr/src/app/data/

    sworm-proxy:
        image: nginx
        container_name: sworm-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/:/etc/nginx/conf.d/:ro
            - ./static/:/usr/share/nginx/html/static/:ro
            - /etc/letsencrypt/archive/sworm.org/:/etc/nginx/ssl/sworm.org/:ro
